#!/bin/sh
#
# $Id: printlog 497 2010-07-13 20:12:26Z jakob $

LOGFILE=$1
COPIES=${2:-1}

if [ ! -f "$LOGFILE" ]; then
	echo "usage: $0 [filename] [copies]"
	exit 1
fi

# approx top margin in postscript points (1 point = 0.353 mm)
# (might need to be adjusted to match the letterhead)
## --margins=left:right:top:bottom
## top_margin=200 #for ICANN header
##--margins=::${top_margin}: \
##--no-header \


# strip keymgmt tools timestams and loglevel, then print using enscript
sed 's/....-..-..T..:..:..Z: \[.*\] //' < $LOGFILE |\
enscript \
	--copies=${COPIES} \
	--font=Courier7.5 \
	--setpagedevice=Collate:true \
	--header=$LOGFILE'||Page $% of $='

