#!/usr/bin/perl
#
# $Id: ttyaudit 564 2010-10-25 06:44:08Z jakob $
#
# Copyright (c) 2010 Kirei AB
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
######################################################################

require 5.6.0;
use warnings;
use strict;

use POSIX qw(strftime);

my $progname = "TTYAUDIT";

sub main {
    if ($#ARGV < 0) {
        print STDERR "usage: ttyaudit [device1] [device2] ... [deviceN]";
        exit(1);
    }

    my $timestamp = strftime("%Y%m%d-%H%M%S", localtime);

    message("Starting");

    foreach my $device (@ARGV) {
        unless (-e $device) {
            message("Device %s not found", $device);
            exit(1);
        }

        message("Setting up audit log for device %s", $device);

        my $tag = $device;
        $tag =~ s,/(dev|tmp)/,,;

        my $logfile = sprintf("ttyaudit-%s-%s.log", $tag, $timestamp);

        my $pid = fork();

        if ($pid) {
            message("Logging device %s to %s (pid=%d)", $device, $logfile,
                $pid);
        } else {
            ttyaudit($device, $tag, $logfile);
            message("Device %s finished (pid=%d)", $device, $$);
            exit(0);
        }
    }

    1 while (wait() != -1);

    message("Done");
}

sub ttyaudit {
    my $device  = shift;
    my $tag     = shift;
    my $logfile = shift;

    open(INPUT,  "< $device");
    open(OUTPUT, ">> $logfile");

    while (<INPUT>) {
        chomp;

        my $log = sprintf("%s\t%s\t%s\n", timestamp(), $tag, $_);
        print STDOUT $log;
        print OUTPUT $log;
    }

    close(INPUT);
    close(OUTPUT);
}

sub message {
    my $format = shift;

    printf STDERR (">> %s $format\n", $progname, @_);
}

# return timstamp in ISO 8601:2004 format, e.g. YYYY-MM-DDThh:mm:ssTZD
sub timestamp {
    return strftime("%Y-%m-%dT%H:%M:%S%z", localtime);
}

main;
